services:
  - type: web
    name: healtheye-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 