services:
  # Node.js Express API for HealthEye
  - type: web
    name: healtheye-node-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true